### ISSUE TITLE
Cannot read properties of undefined (reading '_isAMomentObject')

### ISSUE THREAD

**Issue by sergeu90** [mpyw/axios-case-converter#49] opened 2022-10-12 16:45 UTC
After upgrade to new version. I getting error. My value is moment js date.

**Comment by mpyw** [comment] 2022-10-13 14:45
> After upgrade to new version.

No, it's reproducible since version `axios-case-convereter@0.9.0` and `axios@0.27.2`. The transforming logic has not been changed.

> My value is moment js date.

In short, don't pass `moment()` directly into the payload. Call `moment().toJSON()` explicitly.

----

Optionally, we can reverse **[`transformRequest` options order](https://github.com/mpyw/axios-case-converter/blob/8d6ef9dadb58b213570b32e5f3189a66eff4bcba/src/middleware.ts#L67-L73)** to precede **[axios default transformer](https://github.com/axios/axios/blob/1b29f4e98e5bb44a125230398f61aa5b0add91c2/dist/node/axios.cjs#L2965-L3023
)** execution.

However, this would be a breaking change. In addition, we need to restore its original type after it has been transformed into string. Therefore, without a well-tested PR, there are no plans to accept the change so far.

**Comment by mpyw** [comment] 2022-10-13 14:58
As an another option,

**Comment by mpyw** [comment] 2022-10-13 15:05
Still [`isPlainObject`](https://github.com/mpyw/axios-case-converter/blob/8d6ef9dadb58b213570b32e5f3189a66eff4bcba/src/util.ts#L13-L19) logic should be fixed, okay

**Closed** 2022-10-13 17:25 UTC
